# Generated by Django 4.1.4 on 2022-12-26 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'new_recruits',
            },
        ),
        migrations.CreateModel(
            name='under_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('particular', models.CharField(max_length=200)),
                ('lf', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=20)),
                ('price', models.FloatField(max_length=200)),
                ('total', models.FloatField(max_length=200)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_carol.person')),
            ],
            options={
                'db_table': 'VARIETY',
            },
        ),
    ]
